name: npm

on:
  release:
    types: [published]

jobs:
  release:
    name: npm
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
     # - name: node
     #   uses: actions/setup-node@v4.0.2
     #   with: 
     #      node-version: 18
     #      always-auth: true
     #      registry-url: https://registry.npmjs.org/
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
